image: slalomtpci/tpci-aws-sam-ref-api-build:0.0.1

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
        after-script:
          - slack-alert.sh ${BITBUCKET_EXIT_CODE} "Test"
